apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizdesk
  template:
    metadata:
      labels:
        app: wizdesk
    spec:
      containers:
      - name: wizdesk
        image: prathi2n/wizdesk:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wizdesk-service
spec:
  type: NodePort
  selector:
    app: wizdesk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
