apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizdesk-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wizdesk
  template:
    metadata:
      labels:
        app: wizdesk
    spec:
      containers:
      - name: wizdesk
        image: prathi2n/wizdesk:latest
        ports:
        - containerPort: 8080
